name: fastapi-videojuegos

services: 
  fastapi-app:  
    build:  
      context: .  
      dockerfile: Dockerfile  
    container_name: fastapi-app-videojuegos 
    restart: always  
    ports:  
      - "8000:8000"  
    depends_on:  
      - fastapi-db  
    environment:
      DATABASE_URL: ${DB_URL}
  fastapi-db:  
    image: postgres:15
    container_name: fastapi-db-videojuegos
    restart: always 
    environment:  
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:  
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: