name: fastapi-postgres

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app-postgres
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db-postgres
  db-postgres:
    image: postgres
    container_name: fastapi-db-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"